# Generated by Django 4.2.7 on 2026-05-08 11:14

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('ranking_model', models.CharField(choices=[('cosine', 'Cosine Similarity'), ('bm25', 'BM25')], max_length=20)),
                ('precision_at_5', models.FloatField(default=0.0)),
                ('precision_at_10', models.FloatField(default=0.0)),
                ('recall', models.FloatField(default=0.0)),
                ('num_results', models.IntegerField(default=0)),
                ('query_time', models.FloatField(default=0.0, help_text='Query time in seconds')),
                ('relevant_docs', models.TextField(blank=True, help_text='JSON list of relevant document IDs')),
                ('retrieved_docs', models.TextField(blank=True, help_text='JSON list of retrieved document IDs')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(db_index=True, max_length=200, unique=True)),
                ('document_frequency', models.IntegerField(default=0)),
                ('postings_list', models.TextField(help_text='JSON: [{doc_id, term_freq, positions}, ...]')),
                ('idf', models.FloatField(default=0.0, help_text='Inverse Document Frequency')),
            ],
            options={
                'ordering': ['term'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('raw_text', models.TextField(help_text='Original document text')),
                ('processed_text', models.TextField(blank=True, help_text='Preprocessed text')),
                ('url', models.URLField(blank=True, null=True)),
                ('pub_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('doc_type', models.CharField(choices=[('txt', 'Text'), ('pdf', 'PDF'), ('html', 'HTML')], default='txt', max_length=10)),
                ('file', models.FileField(blank=True, null=True, upload_to='documents/')),
                ('language', models.CharField(choices=[('amharic', 'Amharic'), ('tigrinya', 'Tigrinya'), ('afan_oromo', 'Afan Oromo'), ('english', 'English'), ('mixed', 'Mixed')], default='english', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_indexed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-pub_date'],
                'indexes': [models.Index(fields=['language'], name='search_docu_languag_0d981d_idx'), models.Index(fields=['is_indexed'], name='search_docu_is_inde_852bda_idx')],
            },
        ),
    ]
