# Generated by Django 4.2.7 on 2026-05-08 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=500)),
                ('ranking_model', models.CharField(default='cosine', max_length=20)),
                ('num_results', models.IntegerField(default=0)),
                ('query_time', models.FloatField(default=0.0, help_text='Seconds')),
                ('searched_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-searched_at'],
            },
        ),
        migrations.AddField(
            model_name='evaluationmetric',
            name='f1_score',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='document',
            name='processed_text',
            field=models.TextField(blank=True, help_text='Preprocessed / tokenised text'),
        ),
        migrations.AlterField(
            model_name='evaluationmetric',
            name='query_time',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='evaluationmetric',
            name='relevant_docs',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='evaluationmetric',
            name='retrieved_docs',
            field=models.TextField(blank=True, default='[]'),
        ),
        migrations.AlterField(
            model_name='indexentry',
            name='idf',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='indexentry',
            name='postings_list',
            field=models.TextField(default='[]'),
        ),
    ]
