# Generated by Django 4.2.7 on 2026-05-30 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_searchlog_evaluationmetric_f1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='concepts',
            field=models.TextField(blank=True, default='[]', help_text='JSON list of key concepts'),
        ),
        migrations.AddField(
            model_name='document',
            name='summary',
            field=models.TextField(blank=True, help_text='Auto-generated extractive summary'),
        ),
    ]
